---
- name: reloading firewalld
  command: firewall-cmd --reload
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

- name: saving iptables
  command: iptables-save
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'"

