---
- name: restart mariadb
  command: systemctl restart mariadb
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

- name: restart mysql
  command: /etc/init.d/mysqld restart
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'"
