---
- name: Adding Database service to internal firewalld
  firewalld:
     service: mysql
     permanent: true
     state: enabled
  notify: reloading firewalld
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

- name: Adding iptables rules 
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 3306
    jump: ACCEPT
    comment: Accept new DB connections
  notify: saving iptables
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'"
     
